config/routes.rb
Pika::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'
  resources :casestudies
  resources :persons
  resources :mailinglists
  resources :organizations
  resources :projects  
  resources :workshops

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

	def new
	
	end

	def create
		render text: params[:persons].inspect
	end
	def get
 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pika</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/persons/new.html.erb
<%= form_for :post, url: persons_path do |f| %>
  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :title %>
  </p>

 <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :title %>
  </p>

 <p>
    <%= f.label :email %><br>
    <%= f.text_field :title %>
 </p>

 <p>
    <%= f.label :password %><br>
    <%= f.text_field :title %>
 </p>
 

<p>
    <%= f.label :address %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :organization %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Landing#index</h1>
<p>Find me in app/views/landing/index.html.erb</p>